version: "3"
services:
  security:
    build: SecurityAnalysis
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql

  dbpostgresql:
    image: postgres
    restart: always
    ports:
        - "5432:5432"
    environment:
      POSTGRES_PASSWORD: userpw
      POSTGRES_DB: sonar_projects
    

